name: C++ CI 

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Singularity
      run: |
        export VERSION=3.8.7 && # adjust this as necessary \
        wget https://github.com/hpcng/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz \
        && sudo tar -xzf singularity-${VERSION}.tar.gz \
        && cd singularity-${VERSION} \
        && sudo ./mconfig \
        && sudo make -C builddir \
        && sudo make -C builddir install
 
    - name : verifyVersion
      run: singularity --version  

    - name: Build Singularity container
      run: |
        sudo singularity build container.sif Singularity.def

    - name: Setup SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ecdsa
        echo "${{ secrets.SSH_CERT }}" > ~/.ssh/id_ecdsa-cert.pub
        chmod 600 ~/.ssh/id_ecdsa
        chmod 644 ~/.ssh/id_ecdsa-cert.pub

    - name: Copy container and scripts to cluster
      run: |
        scp -i ~/.ssh/id_ecdsa \
            -o CertificateFile=~/.ssh/id_ecdsa-cert.pub \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            container.sif rinfasce@login.g100.cineca.it:/g100/home/userexternal/rinfasce/
        scp -i ~/.ssh/id_ecdsa \
            -o CertificateFile=~/.ssh/id_ecdsa-cert.pub \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            job.sh rinfasce@login.g100.cineca.it:/g100/home/userexternal/rinfasce/
        scp -i ~/.ssh/id_ecdsa \
            -o CertificateFile=~/.ssh/id_ecdsa-cert.pub \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            random_gen_images.py rinfasce@login.g100.cineca.it:/g100/home/userexternal/rinfasce/

    - name: Submit job on cluster
      run: |
        ssh -i ~/.ssh/id_ecdsa \
            -o CertificateFile=~/.ssh/id_ecdsa-cert.pub \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            rinfasce@login.g100.cineca.it "cd /g100/home/userexternal/rinfasce && sbatch job.sh"
